basePath: /
info:
  contact: {}
  description: This is a sample server celler server.
  title: CRUD Users
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: List all users
      parameters:
      - description: Search User by Name
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: string
          schema:
            type: string
      tags:
      - users
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Detail user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: string
          schema:
            type: string
      security:
      - Token: []
      tags:
      - users
securityDefinitions:
  Token:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
