basePath: /
info:
  contact: {}
  description: This is a sample server celler server.
  title: CRUD Users
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: list all users
      produces:
      - application/json
      responses:
        "200":
          description: string
          schema:
            type: string
      tags:
      - users
  /users/{id}:
    get:
      consumes:
      - application/json
      description: list all users
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: string
          schema:
            type: string
      tags:
      - users
swagger: "2.0"
